name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
      - name: run test
        run: npm test
      - name: docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: docker build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bot-api:latest .
      - name: docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bot-api:latest
      - name: deploy to Render
        if: success()
        env:
          DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$DEPLOY_HOOK"

